server:
  port: 8882
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848    # Nacos 注册中心地址
  application:
    name: service-zuul #服务名
zuul:
  #将敏感头信息置空，这样就不会将头信息里的token丢失了
  sensitive-headers: Access-Control-Allow-Origin
  ribbon:
    eager-load:
      enabled:  true #饥饿加载
  retryable: true #是否开启重试功能
  ignoredServices: "*"  #禁用掉使用浏览器通过服务名的方式访问服务
  prefix: "/jiuzhe"  #统一访问前缀
  routes:
    shop-server: "/shop/**"
    system-server: "/system/**"
    order-server: "/order/**"
ribbon:
  MaxAutoRetries: 1 #对当前服务的重试次数
  MaxAutoRetriesNextServer: 1 #切换相同Server的次数
  OkToRetryOnAllOperations: false  	#是否所有操作都重试，因为针对post请求如果没做幂等处理可能会造成数据多次添加/修改
  ConnectTimeout: 5000 #链接超时时间
  ReadTimeout: 5000 #读取超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000 #hystrix超时,置thread和semaphore两种隔离策略的超时时间
#MyBatis-Plus相关配置
mybatis-plus:
  #指定Mapper.xml路径，如果与Mapper路径相同的话，可省略
  mapper-locations: classpath:cn/wujiangbo/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰大小写自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台sql输出